// Code generated by go generate; DO NOT EDIT.

package jsonparser

//go:generate go run ./internal/eachkey

import (
	"errors"
	"io"
	"strconv"
)

// SYS-REQ-008, SYS-REQ-085, SYS-REQ-111
func EachKey(data []byte, cb func(int, []byte, ValueType, error), paths ...[]string) int {
	var level, pathsMatched, i int
	ln := len(data)

	pathFlags := make([]bool, stackArraySize)[:]
	if len(paths) > cap(pathFlags) {
		pathFlags = make([]bool, len(paths))[:]
	}
	pathFlags = pathFlags[0:len(paths)]

	var maxPath int
	for _, p := range paths {
		if len(p) > maxPath {
			maxPath = len(p)
		}
	}

	anyArrayPath := hasArrayPath(paths)

	pathsBuf := make([]string, stackArraySize)[:]
	if maxPath > cap(pathsBuf) {
		pathsBuf = make([]string, maxPath)[:]
	}
	pathsBuf = pathsBuf[0:maxPath]

	for i < ln {
		switch data[i] {
		case '"':
			i++
			keyBegin := i

			strEnd, keyEscaped := stringEnd(data[i:])
			if strEnd == -1 {
				return -1
			}
			i += strEnd

			keyEnd := i - 1

			valueOffset := nextToken(data[i:])
			if valueOffset == -1 {
				return -1
			}

			i += valueOffset

			// if string is a key, and key level match
			if data[i] == ':' {
				match := -1
				key := data[keyBegin:keyEnd]

				// for unescape: if there are no escape sequences, this is cheap; if there are, it is a
				// bit more expensive, but causes no allocations unless len(key) > unescapeStackBufSize
				var keyUnesc []byte
				if !keyEscaped {
					keyUnesc = key
				} else {
					var stackbuf [unescapeStackBufSize]byte
					if ku, err := Unescape(key, stackbuf[:]); err != nil {
						return -1
					} else {
						keyUnesc = ku
					}
				}

				if maxPath >= level {
					if level < 1 {
						cb(-1, nil, Unknown, MalformedJsonError)
						return -1
					}

					pathsBuf[level-1] = bytesToString(&keyUnesc)
					for pi, p := range paths {
						if len(p) != level || pathFlags[pi] || !equalStr(&keyUnesc, p[level-1]) || !sameTree(p, pathsBuf[:level]) {
							continue
						}

						match = pi

						pathsMatched++
						pathFlags[pi] = true

						v, dt, _, e := Get(data[i+1:])
						cb(pi, v, dt, e)
						if pathsMatched == len(paths) {
							break
						}
					}
					if pathsMatched == len(paths) {
						return i
					}
				}

				if match == -1 {
					tokenOffset := nextToken(data[i+1:])
					i += tokenOffset
					// i remains just before the value; the outer loop advances to it.
				}

				switch data[i] {
				case '{', '}', '[', '"':
					i--
				}
			} else {
				i--
			}
		case '{':
			level++
		case '}':
			level--
		case '[':
			if level < 0 {
				cb(-1, nil, Unknown, MalformedJsonError)
				return -1
			}

			walked := false
			if anyArrayPath {
				var arrIdxHeads map[int]int32
				var next []int32

				for pi := len(paths) - 1; pi >= 0; pi-- {
					p := paths[pi]
					// Skip empty components and paths that do not target this array.
					if len(p) < level+1 || pathFlags[pi] || len(p[level]) == 0 || p[level][0] != '[' || !sameTree(p, pathsBuf[:level]) {
						continue
					}

					indexComponent := p[level]
					if len(indexComponent) < 3 || indexComponent[len(indexComponent)-1] != ']' {
						continue
					}
					aIdx, err := strconv.Atoi(indexComponent[1 : len(indexComponent)-1])
					if err != nil {
						continue
					}
					if next == nil {
						arrIdxHeads = make(map[int]int32)
						next = make([]int32, len(paths))
					}
					// Prepending in reverse path order preserves ascending callback order.
					next[pi] = arrIdxHeads[aIdx]
					arrIdxHeads[aIdx] = int32(pi) + 1
				}

				if len(arrIdxHeads) > 0 {
					level++
					walked = true

					var curIdx int
					arrOff, _ := ArrayEach(data[i:], func(value []byte, dataType ValueType, offset int, err error) {
						for link := arrIdxHeads[curIdx]; link != 0; link = next[link-1] {
							pi := int(link) - 1
							if pathFlags[pi] {
								continue
							}
							p := paths[pi]

							if level == len(p) {
								// ArrayEach has already parsed the terminal value.
								// In particular, string values do not include their
								// quotes and therefore cannot be reparsed by Get.
								pathsMatched++
								pathFlags[pi] = true
								cb(pi, value, dataType, err)
								continue
							}

							of := searchKeys(value, p[level:]...)
							if of == -1 {
								continue
							}

							v, dt, _, e := Get(value[of:])
							pathsMatched++
							pathFlags[pi] = true
							cb(pi, v, dt, e)
						}

						curIdx += 1
					})
					if pathsMatched == len(paths) {
						return i
					}

					i += arrOff - 1
				}
			}

			if !walked {
				// Do not search for keys inside arrays
				if arraySkip := blockEnd(data[i:], '[', ']'); arraySkip == -1 {
					return -1
				} else {
					i += arraySkip - 1
				}
			}
		case ']':
			level--
		}

		i++
	}

	return -1
}

// EachKeyErr finds the requested paths and allows the callback to stop
// iteration by returning an error. io.EOF stops iteration gracefully.
// SYS-REQ-008
func EachKeyErr(data []byte, cb func(int, []byte, ValueType, error) error, paths ...[]string) error {
	var level, pathsMatched, i int
	ln := len(data)

	pathFlags := make([]bool, stackArraySize)[:]
	if len(paths) > cap(pathFlags) {
		pathFlags = make([]bool, len(paths))[:]
	}
	pathFlags = pathFlags[0:len(paths)]

	var maxPath int
	for _, p := range paths {
		if len(p) > maxPath {
			maxPath = len(p)
		}
	}

	anyArrayPath := hasArrayPath(paths)

	pathsBuf := make([]string, stackArraySize)[:]
	if maxPath > cap(pathsBuf) {
		pathsBuf = make([]string, maxPath)[:]
	}
	pathsBuf = pathsBuf[0:maxPath]

	for i < ln {
		switch data[i] {
		case '"':
			i++
			keyBegin := i

			strEnd, keyEscaped := stringEnd(data[i:])
			if strEnd == -1 {
				return nil
			}
			i += strEnd

			keyEnd := i - 1

			valueOffset := nextToken(data[i:])
			if valueOffset == -1 {
				return nil
			}

			i += valueOffset

			// if string is a key, and key level match
			if data[i] == ':' {
				match := -1
				key := data[keyBegin:keyEnd]

				// for unescape: if there are no escape sequences, this is cheap; if there are, it is a
				// bit more expensive, but causes no allocations unless len(key) > unescapeStackBufSize
				var keyUnesc []byte
				if !keyEscaped {
					keyUnesc = key
				} else {
					var stackbuf [unescapeStackBufSize]byte
					if ku, err := Unescape(key, stackbuf[:]); err != nil {
						return nil
					} else {
						keyUnesc = ku
					}
				}

				if maxPath >= level {
					if level < 1 {
						callbackErr := cb(-1, nil, Unknown, MalformedJsonError)
						if callbackErr != nil && !errors.Is(callbackErr, io.EOF) {
							return callbackErr
						}
						return nil
					}

					pathsBuf[level-1] = bytesToString(&keyUnesc)
					for pi, p := range paths {
						if len(p) != level || pathFlags[pi] || !equalStr(&keyUnesc, p[level-1]) || !sameTree(p, pathsBuf[:level]) {
							continue
						}

						match = pi

						pathsMatched++
						pathFlags[pi] = true

						v, dt, _, e := Get(data[i+1:])
						if callbackErr := cb(pi, v, dt, e); callbackErr != nil {
							if errors.Is(callbackErr, io.EOF) {
								return nil
							}
							return callbackErr
						}
						if pathsMatched == len(paths) {
							break
						}
					}
					if pathsMatched == len(paths) {
						return nil
					}
				}

				if match == -1 {
					tokenOffset := nextToken(data[i+1:])
					i += tokenOffset
					// i remains just before the value; the outer loop advances to it.
				}

				switch data[i] {
				case '{', '}', '[', '"':
					i--
				}
			} else {
				i--
			}
		case '{':
			level++
		case '}':
			level--
		case '[':
			if level < 0 {
				callbackErr := cb(-1, nil, Unknown, MalformedJsonError)
				if callbackErr != nil && !errors.Is(callbackErr, io.EOF) {
					return callbackErr
				}
				return nil
			}

			walked := false
			if anyArrayPath {
				var arrIdxHeads map[int]int32
				var next []int32

				for pi := len(paths) - 1; pi >= 0; pi-- {
					p := paths[pi]
					// Skip empty components and paths that do not target this array.
					if len(p) < level+1 || pathFlags[pi] || len(p[level]) == 0 || p[level][0] != '[' || !sameTree(p, pathsBuf[:level]) {
						continue
					}

					indexComponent := p[level]
					if len(indexComponent) < 3 || indexComponent[len(indexComponent)-1] != ']' {
						continue
					}
					aIdx, err := strconv.Atoi(indexComponent[1 : len(indexComponent)-1])
					if err != nil {
						continue
					}
					if next == nil {
						arrIdxHeads = make(map[int]int32)
						next = make([]int32, len(paths))
					}
					// Prepending in reverse path order preserves ascending callback order.
					next[pi] = arrIdxHeads[aIdx]
					arrIdxHeads[aIdx] = int32(pi) + 1
				}

				if len(arrIdxHeads) > 0 {
					level++
					walked = true

					var curIdx int
					var callbackErr error
					var stopped bool
					arrOff, _, _ := arrayEachErr(data[i:], func(value []byte, dataType ValueType, offset int, err error) error {
						for link := arrIdxHeads[curIdx]; link != 0; link = next[link-1] {
							pi := int(link) - 1
							if pathFlags[pi] {
								continue
							}
							p := paths[pi]

							if level == len(p) {
								// ArrayEach has already parsed the terminal value.
								// In particular, string values do not include their
								// quotes and therefore cannot be reparsed by Get.
								pathsMatched++
								pathFlags[pi] = true
								callbackErr = cb(pi, value, dataType, err)
								if callbackErr != nil {
									stopped = true
									return callbackErr
								}
								continue
							}

							of := searchKeys(value, p[level:]...)
							if of == -1 {
								continue
							}

							v, dt, _, e := Get(value[of:])
							pathsMatched++
							pathFlags[pi] = true
							callbackErr = cb(pi, v, dt, e)
							if callbackErr != nil {
								stopped = true
								return callbackErr
							}
						}

						curIdx += 1
						return nil
					})
					if stopped {
						if errors.Is(callbackErr, io.EOF) {
							return nil
						}
						return callbackErr
					}
					if pathsMatched == len(paths) {
						return nil
					}

					i += arrOff - 1
				}
			}

			if !walked {
				// Do not search for keys inside arrays
				if arraySkip := blockEnd(data[i:], '[', ']'); arraySkip == -1 {
					return nil
				} else {
					i += arraySkip - 1
				}
			}
		case ']':
			level--
		}

		i++
	}

	return nil
}
